services:
    postgres:
        image: postgres:18.4-alpine
        container_name: ai-prompts-vault-api-postgres
        restart: no
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: '${DATABASE_USER}'
            POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
            POSTGRES_DB: '${DATABASE_DB}'
        volumes:
            - pgdata:/var/lib/postgresql
volumes:
    pgdata:
